### ISSUE TITLE
Settings screen is overflowing

### ISSUE THREAD

**Issue by AksV73** [himanshusharma89/relic_bazaar#166]
# Bug Report 🐛
My phone is of a smaller size. Similar to the login screen, the settings screen is overflowing in my phone.
I would like to solve this by placing a vertical scroll.
Can I take it up ?

**Comment by Mus2413** [comment]
Hello, I am Gssoc'21 participant . I would like to contribute on this project. Could you please assign me this issue.

**Comment by himanshusharma89** [comment]
I suppose I have already assigned another issue to @AksV73, so sure @Mus2413. Also, do check out the pinged messages on the relic bazaar channel in Discord for few pointers before contributing. For this issue, make the screen responsive and decrease the font size of the items, also use StackedContainer instead of Stack for the background UI.

**Comment by Mus2413** [comment]
Thank you for assigning it .

**Comment by Mus2413** [comment]
How much time I have to complete this task?

**Comment by himanshusharma89** [comment]
> How much time I have to complete this task?

Within 2 days.
