### ISSUE TITLE
Profile Screen Update

### ISSUE THREAD

**Issue by himanshusharma89** [himanshusharma89/relic_bazaar#39]
- [ ] Update the current profile screen and show the user details and buttons to navigate to the "Your Orders" and "Wishlist" screen: 
- [x] Add menu icon to the top right to navigate to the "Settings" screen
- [x] Make the screen responsive for any device.

**Comment by sakshi2707** [comment]
please assign the 'Add menu icon to the top right to navigate to Setting screen" task to me under gssoc'21

**Comment by himanshusharma89** [comment]
Sure @sakshi2707

**Comment by Alifbhanvadiya14** [comment]
@himanshusharma89  I would like to work on "Update the current profile screen and show the user details and buttons to navigate to the "Your Orders" and "Wishlist" screen."

**Comment by himanshusharma89** [comment]
Sure @Alifbhanvadiya14

**Comment by anotherwebguy** [comment]
> * [ ]  Update the current profile screen and show the user details and buttons to navigate to the "Your Orders" and "Wishlist" screen: @Alifbhanvadiya14
> * [ ]  Add menu icon to the top right to navigate to the "Settings" screen: @sakshi2707
> * [ ]  Make the screen responsive for any device.

I would like to work on resolving the overflow issue for small screen size can i work on this @himanshusharma89 ?

**Comment by himanshusharma89** [comment]
Yes @anotherwebguy

**Comment by Alifbhanvadiya14** [comment]
@himanshusharma89 Will be done by Tomorrow

**Comment by SamarpanCoder2002** [comment]
Can I work on that issue...I am also a GSSOC'21 particiapant....Please assign me to here

**Comment by himanshusharma89** [comment]
@SamarpanCoder2002 Sure, but make sure to do it like this:
![image](https://user-images.githubusercontent.com/44980497/113988752-664b4c00-986d-11eb-8eed-1c81290834c3.png)

**Comment by SamarpanCoder2002** [comment]
@himanshusharma89 ... Sir I don't even get into the project....many errors came

<p>
1. <img src="https://user-images.githubusercontent.com/66327336/114318175-7727e600-9b29-11eb-9a1b-89ca42b413a2.png" width="200">
2. <img src="https://user-images.githubusercontent.com/66327336/114318180-7c853080-9b29-11eb-91df-c1b4c236e471.png" width="200">
</p>

Everytime invalid reuqest came.... Even I give the right password and my own email...

Even I can't do Google or Facebook Sign In, everytime Platform Exception Came...

<img src="https://user-images.githubusercontent.com/66327336/114318263-f3bac480-9b29-11eb-9c38-f0326a175602.png" width="1000">

I implement email and password Auth and even Google And Facebook Auth in more than 3 projects of GSSOC and even in my project.... I don't get such kind of error

That may be due to use old plugin version in pubspec.yaml


Even Look at that picture
<img src="https://user-images.githubusercontent.com/66327336/114318409-65930e00-9b2a-11eb-8686-88be2e53288c.png" width="200">

The text is not visible when invalid Request is came..... How Can I forward with that, If I can't take entry.....

Please help me sir @himanshusharma89 .....

Can I raise a new issue to remove that kind of error from the project???????

WAiting for your response @himanshusharma89

**Comment by himanshusharma89** [comment]
@SamarpanCoder2002 The issue is most probably because of the SHA-1 key not being added to the firebase console. Your SHA-1 keys need to be added in the console for auth to be working.

And about the error message, an issue is already raised for that.

**Comment by SamarpanCoder2002** [comment]
> @SamarpanCoder2002 The issue is most probably because of the SHA-1 key not being added to the firebase console. Your SHA-1 keys need to be added in the console for auth to be working.
> 
> And about the error message, an issue is already raised for that.

Ok cool.... please add me with that firebase account.... My Gmail: samarpanofficial2021@gmail.com

**Comment by SamarpanCoder2002** [comment]
@himanshusharma89 I provide my mail to add me with firebase account....

Please response @himanshusharma89....

Otherwise I can't start working on that

**Comment by himanshusharma89** [comment]
@SamarpanCoder2002 Send me your SHA-1 key via Discord, I'll add it to the console.

**Comment by himanshusharma89** [comment]
@SamarpanCoder2002 Any update?

**Comment by SamarpanCoder2002** [comment]
> @SamarpanCoder2002 Any update?

I not noticed your reply.... I will send SHA1 ket in discord

**Comment by SapinderSingh** [comment]
@himanshusharma89 I can work on this issue.
